name: GCP Cloud Run Next.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    permissions:
      contents: 'read'
      id-token: 'write'
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
            project_id: '${{ secrets.GCP_PROJECT_ID }}'

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker gcr.io --quiet

      - name: Create env file
        run: |
          touch .env
          echo NEXT_PUBLIC_ASSET_HOST=${{ secrets.NEXT_PUBLIC_ASSET_HOST }} >> .env
          echo CDN_ADDRESS=${{ secrets.CDN_ADDRESS }} >> .env
          echo NEXT_PUBLIC_APP_TOKEN=${{ secrets.NEXT_PUBLIC_APP_TOKEN }} >> .env
          echo NEXT_PUBLIC_MAPBOX_TOKEN=${{ secrets.NEXT_PUBLIC_MAPBOX_TOKEN }} >> .env
          echo "NEXT_PUBLIC_TRAILBLAZE_API_ENDPOINT=${{ secrets.NEXT_PUBLIC_TRAILBLAZE_API_ENDPOINT }}" >> .env

      - name: Write GCP credentials to file
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > gcp-key.json

      - name: Build Docker image
        run: |
          docker build --secret id=gcp-key,src=gcp-key.json \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/trailblaze-app:$GITHUB_SHA .

      - name: Remove GCP credentials file
        run: rm gcp-key.json

      - name: Push Docker Image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/trailblaze-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: trailblaze-app
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/trailblaze-app:${{ github.sha }}
          region: us-central1
          env_vars: |
            NEXT_PUBLIC_ASSET_HOST=${{ secrets.NEXT_PUBLIC_ASSET_HOST }}
            CDN_ADDRESS=${{ secrets.CDN_ADDRESS }}
            NEXT_PUBLIC_APP_TOKEN=${{ secrets.NEXT_PUBLIC_APP_TOKEN }}
            NEXT_PUBLIC_MAPBOX_TOKEN=${{ secrets.NEXT_PUBLIC_MAPBOX_TOKEN }}
            NEXT_PUBLIC_TRAILBLAZE_API_ENDPOINT=${{ secrets.NEXT_PUBLIC_TRAILBLAZE_API_ENDPOINT }}
